#! /usr/bin/env python
#
# Edit experiment config for given update file
#
# $Id$
#

import argparse
import os

import update
from feedback import die
import package_info


#
# Main routine
#

# Check command line

command_line = argparse.ArgumentParser(description=
    'Edit experiment config for given update file')
command_line.add_argument('update', nargs='?', default='update', 
                          help='update script file name [%(default)s]')
command_line.add_argument('-V', '--version', action='version',
                          version=package_info.version)

args = command_line.parse_args()

try:
    update_data = update.Update(args.update)
    editor = os.environ.get('VISUAL', os.environ.get('EDITOR', 'vi'))
    os.execlp(editor, editor, update_data.get_config_file())
except IOError as error:
    die("'{0}': {1}".format(error.filename, error.strerror))

